# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/0.13.3/tag_publish/schema.json

docker:
  images:
    - name: camptocamp/mapserver
      tags:
        - '{version}'
        - '{version}-arm64'
  repository:
    github:
      host: ghcr.io
      versions_type:
        - tag
        - default_branch
        - stabilization_branch
    dockerhub:
      host: docker.io
      versions_type:
        - tag
        - default_branch
        - stabilization_branch

dispatch:
  - {}
