#!/bin/bash -eux

if [ "$#" -ne 1 ]; then
    echo "Usage: checkout_release.sh {BRANCH}"
    echo
    echo "Checkout the last tag matching final-* of the given branch"
    exit 1
fi

BRANCH=$1
TAG_PREFIX=${BRANCH//branch-/rel-}

git fetch --tags
LAST_RELEASE=$(git log --format=%H "--tags=$TAG_PREFIX*" --no-walk | head -1)
if [ -z "$LAST_RELEASE" ]; then
    echo "No release found for branch $BRANCH"
else
    git checkout --detach "$LAST_RELEASE"
fi

echo
echo "Will build: -----------------------------------------"
git log -n 1 --decorate
echo "-----------------------------------------------------"
echo
