#!/bin/bash -eux

if [ $# -gt 0 ]
then
  TAG="$1"
elif [[ "${GITHUB_REF}" == "refs/heads/master" ]]
then
  TAG=latest
elif [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]
then
  TAG=$(echo "${GITHUB_REF}"|sed 's|^refs/tags/||g')
elif [[ "${GITHUB_REF}" =~ ^refs/heads/.* ]]
then
  TAG=$(echo "${GITHUB_REF}"|sed 's|^refs/heads/||g')
else
  echo Wrong ref: ${GITHUB_REF}
  exit 2
fi

docker tag camptocamp/mapserver camptocamp/mapserver:${TAG}
docker push camptocamp/mapserver:${TAG}
