name: Clean docker hub tags

on:
  delete:
  pull_request:
    types:
      - closed

jobs:
  clean:
    name: Clean docker hub tags
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker

      - run: |
          sudo rm /etc/apt/sources.list.d/*.list
          sudo apt update
          sudo apt install --yes python3-wheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: sudo python3 -m pip install --requirement=ci/requirements.txt
      - name: Clean Docker hub tags
        run: c2cciutils-clean
